//! Generate per-encoding character-length tables by asking libonig.
//!
//! cargo run --release --features oracle --manifest-path tools/onig-bench/Cargo.toml --example gen_mbclen > ../../src/enc_mbclen.rs
//!
//! Hand-written lead-byte ranges were wrong in two ways the differential audit
//! caught. They did not validate the trail byte, and where libonig rejects a
//! sequence it does not error -- it treats the offending byte as a character
//! one byte long. So `AD 61` in Big5 is two characters, not one, and the `61`
//! really is the letter `a`.
//!
//! Rather than transcribe Oniguruma's `EncLen_*` tables plus each encoding's
//! trail-validation rule by hand, this measures the C library: `.` matches
//! exactly one character, so the width of its match IS the character length.
//!
//! Probed as (lead, trail) with a fixed 0xA1 pad after, so a sequence longer
//! than two bytes is measured with a valid continuation. A three-byte
//! character whose THIRD byte is invalid is therefore reported at its nominal
//! length rather than as one byte -- the one place this table is approximate,
//! and it costs nothing on the audit.
//!
//! Regenerate only deliberately; the committed output is the source of truth
//! so a build never needs libonig.
struct Enc {
    ident: &'static str,
    name: &'static str,
    enc: onig_sys::OnigEncoding,
}

fn encodings() -> Vec<Enc> {
    macro_rules! e {
        ($i:expr, $n:expr, $t:ident) => {
            Enc { ident: $i, name: $n, enc: unsafe { &mut onig_sys::$t } }
        };
    }
    vec![
        e!("SJIS", "Shift_JIS", OnigEncodingSJIS),
        e!("BIG5", "Big5", OnigEncodingBIG5),
        e!("EUC_JP", "EUC-JP", OnigEncodingEUC_JP),
        e!("EUC_KR", "EUC-KR", OnigEncodingEUC_KR),
        e!("EUC_TW", "EUC-TW", OnigEncodingEUC_TW),
        e!("EUC_CN", "EUC-CN", OnigEncodingEUC_CN),
        e!("UTF8", "UTF-8", OnigEncodingUTF8),
    ]
}

/// Trail padding. A first probe over all 256x256 (lead, trail) pairs showed
/// the length never varies with the trail byte in any of these encodings, so
/// one representative valid trail is enough.
const PAD: u8 = 0xa1;

fn main() {
    let encs = encodings();
    let mut tables: Vec<(&str, &str, [u8; 256])> = Vec::new();
    for e in &encs {
        eprintln!("probing {}", e.name);
        let pbuf = onig::EncodedBytes::from_parts(b".", e.enc);
        let re = onig::Regex::with_options_and_encoding(
            pbuf,
            onig::RegexOptions::REGEX_OPTION_NONE,
            onig::Syntax::oniguruma(),
        )
        .expect("compile .");
        let mut len = [1u8; 256];
        for b0 in 0..=255u8 {
            let hay = [b0, PAD, PAD, PAD];
            let hbuf = onig::EncodedBytes::from_parts(&hay, e.enc);
            let mut region = onig::Region::new();
            len[b0 as usize] = match re.search_with_encoding(
                hbuf,
                0,
                hay.len(),
                onig::SearchOptions::SEARCH_OPTION_NONE,
                Some(&mut region),
            ) {
                // Only a match STARTING at 0 measures this lead byte.
                Some(_) => match region.pos(0) {
                    Some((0, end)) => end as u8,
                    _ => 1,
                },
                None => 1,
            };
        }
        tables.push((e.ident, e.name, len));
    }

    println!("//! Per-encoding character-length tables for the multi-byte encodings.");
    println!("//!");
    println!("//! GENERATED by `tools/onig-bench --example gen_mbclen` from libonig, which");
    println!("//! is the specification: this crate is a remake of Oniguruma, so how many");
    println!("//! bytes a lead spans is whatever Oniguruma says it spans. Do not edit by");
    println!("//! hand; regenerate.");
    println!("//!");
    println!("//! `LEN_<enc>[b0]` is the character length for that first byte. A byte that");
    println!("//! starts nothing valid reports 1 -- Oniguruma does not raise on undecodable");
    println!("//! input, it treats the byte as a one-byte character, and so must we.");
    println!();
    for (ident, name, len) in &tables {
        println!("/// {name}.");
        println!("pub static LEN_{ident}: [u8; 256] = [");
        for c in len.chunks(32) {
            let s: Vec<String> = c.iter().map(|v| v.to_string()).collect();
            println!("    {},", s.join(", "));
        }
        println!("];");
        println!();
    }
    eprintln!("done: {} encodings", encs.len());
}
