//! Generate per-encoding ctype tables by asking libonig.
//!
//! cargo run --release --features oracle --manifest-path tools/onig-bench/Cargo.toml --example gen_ctype > ../../src/enc_ctype.rs
//!
//! We are a remake of Oniguruma, so Oniguruma's own ctype tables are the
//! specification for what `\w`, `\d`, `\s` and the POSIX brackets mean in each
//! non-Unicode encoding. Rather than transcribe them by hand -- 128 entries per
//! class per encoding, and every one a chance to fumble -- this asks the C
//! library directly, one byte at a time, and emits ASCII Rust.
//!
//! Regenerate only deliberately; the committed output is the source of truth so
//! a build never needs libonig.

struct Enc {
    ident: &'static str,
    name: &'static str,
    enc: onig_sys::OnigEncoding,
}

fn encodings() -> Vec<Enc> {
    macro_rules! e {
        ($i:expr, $n:expr, $t:ident) => {
            Enc {
                ident: $i,
                name: $n,
                enc: unsafe { &mut onig_sys::$t },
            }
        };
    }
    vec![
        e!("ASCII", "ASCII", OnigEncodingASCII),
        e!("ISO_8859_1", "ISO-8859-1", OnigEncodingISO_8859_1),
        e!("ISO_8859_2", "ISO-8859-2", OnigEncodingISO_8859_2),
        e!("ISO_8859_3", "ISO-8859-3", OnigEncodingISO_8859_3),
        e!("ISO_8859_4", "ISO-8859-4", OnigEncodingISO_8859_4),
        e!("ISO_8859_5", "ISO-8859-5", OnigEncodingISO_8859_5),
        e!("ISO_8859_6", "ISO-8859-6", OnigEncodingISO_8859_6),
        e!("ISO_8859_7", "ISO-8859-7", OnigEncodingISO_8859_7),
        e!("ISO_8859_8", "ISO-8859-8", OnigEncodingISO_8859_8),
        e!("ISO_8859_9", "ISO-8859-9", OnigEncodingISO_8859_9),
        e!("ISO_8859_10", "ISO-8859-10", OnigEncodingISO_8859_10),
        e!("ISO_8859_11", "ISO-8859-11", OnigEncodingISO_8859_11),
        e!("ISO_8859_13", "ISO-8859-13", OnigEncodingISO_8859_13),
        e!("ISO_8859_14", "ISO-8859-14", OnigEncodingISO_8859_14),
        e!("ISO_8859_15", "ISO-8859-15", OnigEncodingISO_8859_15),
        e!("ISO_8859_16", "ISO-8859-16", OnigEncodingISO_8859_16),
        e!("KOI8_R", "KOI8-R", OnigEncodingKOI8_R),
        e!("CP1251", "CP1251", OnigEncodingCP1251),
    ]
}

/// One bit per class, matching `EncCtype` in the engine.
const CLASSES: &[(&str, &str)] = &[
    ("WORD", r"\w"),
    ("DIGIT", r"\d"),
    ("SPACE", r"\s"),
    ("ALPHA", "[[:alpha:]]"),
    ("UPPER", "[[:upper:]]"),
    ("LOWER", "[[:lower:]]"),
    ("ALNUM", "[[:alnum:]]"),
    ("PUNCT", "[[:punct:]]"),
    ("PRINT", "[[:print:]]"),
    ("GRAPH", "[[:graph:]]"),
    ("CNTRL", "[[:cntrl:]]"),
    ("XDIGIT", "[[:xdigit:]]"),
];

/// Does `pat` match the single byte `b`, whole, in this encoding?
fn matches(enc: onig_sys::OnigEncoding, pat: &str, b: u8) -> bool {
    let pbuf = onig::EncodedBytes::from_parts(pat.as_bytes(), enc);
    let re = match onig::Regex::with_options_and_encoding(
        pbuf,
        onig::RegexOptions::REGEX_OPTION_NONE,
        onig::Syntax::oniguruma(),
    ) {
        Ok(r) => r,
        Err(_) => return false,
    };
    let hay = [b];
    let hbuf = onig::EncodedBytes::from_parts(&hay, enc);
    let mut region = onig::Region::new();
    match re.search_with_encoding(
        hbuf,
        0,
        1,
        onig::SearchOptions::SEARCH_OPTION_NONE,
        Some(&mut region),
    ) {
        Some(_) => region.pos(0) == Some((0, 1)),
        None => false,
    }
}

fn main() {
    println!("//! Per-encoding character-class tables for the non-Unicode encodings.");
    println!("//!");
    println!("//! GENERATED by `tools/onig-bench --example gen_ctype` from libonig, which");
    println!("//! is the specification: this crate is a remake of Oniguruma, so what `\\w`");
    println!("//! means in Shift_JIS is whatever Oniguruma says it means. Do not edit by");
    println!("//! hand; regenerate.");
    println!("//!");
    println!("//! One `u16` per byte 0x80..=0xFF. Bytes below 0x80 use the ASCII rules and");
    println!("//! are not stored.");
    println!();
    for (i, (name, _)) in CLASSES.iter().enumerate() {
        println!("pub const {name}: u16 = 1 << {i};");
    }
    println!();

    let encs = encodings();
    for e in &encs {
        eprintln!("generating {}", e.name);
        println!("/// {} -- bytes 0x80..=0xFF.", e.name);
        println!("pub static {}: [u16; 128] = [", e.ident);
        for chunk_start in (0x80u16..=0xFF).step_by(8) {
            let mut row = String::from("    ");
            for b in chunk_start..(chunk_start + 8).min(0x100) {
                let mut bits = 0u16;
                for (i, (_, pat)) in CLASSES.iter().enumerate() {
                    if matches(e.enc, pat, b as u8) {
                        bits |= 1 << i;
                    }
                }
                row.push_str(&format!("0x{bits:04x}, "));
            }
            println!("{}", row.trim_end());
        }
        println!("];");
        println!();
    }

    println!("/// Table for an encoding, or `None` when the engine should use its");
    println!("/// Unicode path instead.");
    println!("pub fn table(name: &str) -> Option<&'static [u16; 128]> {{");
    println!("    Some(match name {{");
    for e in &encs {
        println!("        {:?} => &{},", e.name, e.ident);
    }
    println!("        _ => return None,");
    println!("    }})");
    println!("}}");
    eprintln!("done: {} encodings x {} classes x 128 bytes", encs.len(), CLASSES.len());
}
